# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - configportalakgapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x' # Ensure this matches your App Service Node.js version

      - name: npm install and build
        run: |
          npm install # Installs all dependencies including dev
          npm run build # Builds your Next.js app, creating the .next folder

      - name: Run tests (optional)
        run: npm run test --if-present
        continue-on-error: true # Allow deployment even if tests fail, but mark job as yellow

      - name: Archive production build for deployment
        # ONLY include what's necessary for the App Service runtime:
        # .next/ - The compiled Next.js application
        # public/ - Static assets you want served
        # package.json - Required for 'npm start' on App Service
        # next.config.js - If you have one, often needed for runtime configuration
        # yarn.lock / pnpm-lock.yaml - if you use yarn/pnpm
        run: |
          tar -czf release.tar.gz \
            .next/ \
            public/ \
            package.json \
            next.config.js \
            # Add other necessary root files if any (e.g., global.d.ts, .env if not using App Service Config)

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.tar.gz # Changed to .tar.gz for Linux native archiving

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
          path: . # Download to current directory

      - name: Unpack artifact for deployment
        run: tar -xzf release.tar.gz

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'configportalakgapp'
          slot-name: 'Production'
          package: . # Deploy everything in the current directory
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_4972E66EFCD44AF78AFDBD6F65048866 }}